### ISSUE TITLE
Separate strings out to a different file

### ISSUE THREAD

**Issue by JackKiefer** [JackKiefer/herms#11]
When we're starting to have folks translate herms, it will be easiest to have a separate file where all of the strings that are shown to the user are stored. That way, different files can be loaded for different languages.

Tips:
- Put the file into the `data/` directory.
- Go ahead and just set the filename as a global constant similar to `recipes.herms`. We'll deal with loading other files later when we implement configuration :)

**Comment by Jorissss** [comment]
I'd like to take this!

**Comment by JackKiefer** [comment]
Nope! Just get something working, really. :)

**Comment by siddharthist** [comment]
This is done! If anyone has the commit in which it was done on hand, please comment with a link here (for archival/reference purposes)
