### ISSUE TITLE
Add the option to specify serving size in the "add" menu

### ISSUE THREAD

**Issue by JackKiefer** [JackKiefer/herms#13]
Herm's by default assumes that each recipe is for one serving, but sometimes you might be trying to copy over a recipe thats written by default for multiple servings. Add a box to specify the recipe's serving size in the "add" menu so that Herm's will do the math for you! Still, however, store the recipe as a single serving. So, you'll need to make sure that each quantity gets divided by the user-specified serving size for storage.

**Comment by pdfrod** [comment]
So, this feature implies adding more information to the Recipes file, which would break compatibility with existing Recipes file. Should we worry about it?

**Comment by JackKiefer** [comment]
We're still small enough a project that backwards compatibility isn't a real concern yet. I feel that this is an important enough feature to justify breaking the recipes file.

**Comment by vrom911** [comment]
@pdfrod this feature won't affect Recipes file, as I understand it. All recipes now are assumed to be for single serving, so will new recipes. The thing that should be done is some calculation before adding the recipe.
Am I getting it right, @JackKiefer ?

**Comment by JackKiefer** [comment]
@vrom911 I'm a bit torn on this one... It would be a bit of a pain to refactor everything, but I think we should ultimately include serving size in the recipe data type. Some recipes are just meant for certain serving sizes (I'm thinking big things like cooking a whole turkey). 

What do you guys think?

**Comment by vrom911** [comment]
@JackKiefer  after thinking a bit, I also end up with the fact that it will be more useful to keep it. Also it's better for editing purposes, if user who just input some recipe for `n` servings and in a minute understood that made some mistake, he would expect to see exactly the data he inputted when running `edit` option.. That is another reason to include it in data type.

Btw, @JackKiefer , @pdfrod does anybody already start working on this one? Or I can start with it?

**Comment by pdfrod** [comment]
@vrom911 I agree that in terms of user experience, it's better to save the serving size.

I've already started work on this.

**Comment by JackKiefer** [comment]
Awesome! I'm glad we agree on this. Thank you for your heroic refactoring @pdfrod

**Comment by JackKiefer** [comment]
Implemented by #27!
