### ISSUE TITLE
Add these features to recipe listing

### ISSUE THREAD

**Issue by JackKiefer** [JackKiefer/herms#16]
Things look great with recipe listing! Let's see if we can take it even further.

Add terminal colors and bolded output to make listed recipes easier to read. While you're at it, maybe throw some colors in recipe display too...

Add a flag to generate just a simple list of recipe names without numbers, descriptions, or tags. This would be useful if there is, say, a bash script that interacts with Herm's in some way.

Tips:
- Study the `list` function
- Check out `System.Console.ANSI`

**Comment by pdfrod** [comment]
I'd like to take a shot at this one, if no one's working on it yet.

**Comment by JackKiefer** [comment]
Don't believe anyone is. Go for it!

**Comment by JackKiefer** [comment]
Implemented by #35!
