### ISSUE TITLE
Switch command-line argument handling over to use optparse-applicative

### ISSUE THREAD

**Issue by JackKiefer** [JackKiefer/herms#17]
We've got kind of a terrible system at the moment for argument handling. Let's use a nice library!

- https://hackage.haskell.org/package/optparse-applicative

**Comment by vrom911** [comment]
Can I get this one started within the Hacktoberfest?
I'm currently writing a project where I use `optparse-applicative` and would like to apply it here as well.

**Comment by JackKiefer** [comment]
Absolutely! Especially if you're already familiarizing yourself with the library. I'll throw the Hacktoberfest label in, too. 

Let me know if you have any questions! :)

**Comment by JackKiefer** [comment]
Merged #19
