### ISSUE TITLE
Allow Vim directional keys (h, j, k, l) in the "Add a Recipe" menu

### ISSUE THREAD

**Issue by JackKiefer** [JackKiefer/herms#23]
Currently, you can use Ctrl + the standard directional keys to move around the "Add a Recipe" menu. In the spirit of a true Vim disciple, I tried also allowing the option of Ctrl + (h, j, k, l), but Brick was being weird about it and wouldn't allow you to use some of the directions for some reason.

Your quest is to implement this capability!

- All of the code for the "Add a Recipe" menu is in ``src/AddCLI.hs``
- The library that lets us have this menu is called Brick. If you're new to the library, check out this helpful [introduction](https://samtay.github.io/articles/brick.html) as well as the [hackage documentation](https://hackage.haskell.org/package/brick). It ain't as scary as it looks.
- You are required to use Vim when making edits to the code for this feature (just kidding)

**Comment by rstefanic** [comment]
I'll take a shot at this, but I'm wondering why it wouldn't allow you to add these event listeners when you tried it.

Did you get some specific error?

**Comment by JackKiefer** [comment]
@rstefanic I don't think there was a specific error or anything. I think it was compiling just fine, but for some reason ``Ctrl + k`` and ``Ctrl + l`` were working but not ``Ctrl + j`` or ``Ctrl + h`` (or something to that effect). There might be some sort of hotkey conflict, but I'm not sure.

**Comment by pdfrod** [comment]
It seems that input handling on terminals is much messier than one would expect. For example `Ctrl + j` is interpreted as `Return`, and it's very hard or downright impossible to overcome that. [Graphics.Vty.Input](https://hackage.haskell.org/package/vty-5.18.1/docs/Graphics-Vty-Input.html) has a note mentioning __Terminal Input is Broken__.

**Comment by JackKiefer** [comment]
Aha, that's the kicker. Alrighty, then. Are there any other modifier keys that could potentially allow one to use hjkl? Perhaps `alt`?

**Comment by JackKiefer** [comment]
Implemented by #33!
