### ISSUE TITLE
herms: Prelude.read: no parse on WSL

### ISSUE THREAD

**Issue by DancingQuanta** [JackKiefer/herms#44]
I tried `herms` out on [Windows subsystem for Linux (WSL)](https://docs.microsoft.com/en-gb/windows/wsl/about).

I tried adding a recipe by `herms add`. At the end I received this message
```
herms: Prelude.read: no parse
```
I checked that my new recipe is not saved because `herms view` does not show this recipe.

Could this be due to WSL or bad input (PEBCAK)?

**Comment by DancingQuanta** [comment]
I think it is a human error that causes the error.
I need to investigate which field do not like my input.

**Comment by DancingQuanta** [comment]
In what format do the tags needs to be inputted?

**Comment by JackKiefer** [comment]
Hmm. Tags ought to be space separated; maybe we should mention that somewhere... If you could post a screenshot of your input that is causing the error, that might help us diagnose the problem.

**Comment by DancingQuanta** [comment]
I actually wanted to ask for multi word tags if possible. Tags could be
separated by ,

**Comment by JackKiefer** [comment]
Certainly. That wouldn't be too difficult a feature to implement.

**Comment by JackKiefer** [comment]
Hey @DancingQuanta!

I know it's been a few months, but as of 1d35af094ac2e8455024eb03fb18e76269ddeea0 this feature is now supported! It will now check if your tags input contains commas and, if it does, will assign the tags appropriately. :)

Thanks for the feature suggestion!
