### ISSUE TITLE
Import/export recipes as JSON

### ISSUE THREAD

**Issue by Qwertie-** [JackKiefer/herms#45]
Every language has a library to handle JSON so storing the recipes in the JSON format would make moving recipes to and from other programs much simpler.

**Comment by JackKiefer** [comment]
Hmm, I'm not sure about storing all of the recipes in JSON... That would break backwards compatibility and give a slight overhead increase to reading/writing recipes if it has to convert to JSON every time. I think it would be super cool to export and import recipes as JSON, though!

**Comment by Csear007** [comment]
Yeah I think importing and exporting json would be much more practical

**Comment by JackKiefer** [comment]
Awesome! I was playing around with [aeson](https://hackage.haskell.org/package/aeson) the other day, and it doesn't seem too difficult. I'll add some tags for whoever wants to take a stab at it!

**Comment by Qwertie-** [comment]
@JackKiefer I don't think converting to json will have any noticeable overhead unless you are saving a recipe 60 times a second.

**Comment by Qwertie-** [comment]
@JackKiefer If there was some way to detect the current format and automatically change it to a new JSON format what would you think about using that by default? I think storing the data as JSON even for use within herms would be quite handy, there could be extra info in the file such as a version number for the file, software and version used to create the file and maybe some other stuff, that way changing the file in the future would be super simple as you could just read the file version and know which actions need to be taken to bring it to the latest version. It also means anyone could write a tool for reading and writing data saved/used by herms in any language because JSON works everywhere. A web app for example could be made quite easily for herms files.
 
The performance of aeson is pretty good as well

```
Parsing performance on a late 2013 MacBook Pro (2.6GHz Core i7), running 64-bit GHC 7.10.1, for mostly-English tweets from Twitter's JSON search API:

    6.4 KB payloads, English: 7570 msg/sec (47.6 MB/sec)

    14.6 KB payloads, Japanese: 3261 msg/sec (46.6 MB/sec)

Encoding performance on the same machine and data:

    6.4 KB payloads, English: 22738 msg/sec (142.9 MB/sec)

    14.6 KB payloads, Japanese: 15911 msg/sec (227.4 MB/sec)
```

**Comment by JackKiefer** [comment]
@Qwertie- Ooh, I suppose I hadn't considered that. Yeah! That actually sounds like a really cool way to go about it. You know what, go for it!

**Comment by DancingQuanta** [comment]
As anyone seen this [Open recipe format](http://open-recipe-format.readthedocs.io/en/latest/)?

**Comment by srid** [comment]
@JackKiefer Have you considered using [Dhall](http://dhall-lang.org/) for the cookbook format? You get Haskell's type safety (and other nice features like multiline string) while also supporting JSON export.

**Comment by siddharthist** [comment]
I am working on changing over all internal storage to a YAML format. This involves making `toJSON` and `fromJSON` instances for all our data structures, which should make finishing up this issue a lot easier.

My ideas on file formats:
 - I want something that is portable across programming languages (for now, this rules out Dhall).
 - JSON import/export is great, and we should definitely implement that for interoperability
 - I think YAML is easiest to write by hand, and my ultimate goal is to have (the option of) a more file-based interface (see #37). 

Ultimately, I think it is a good idea to export to all of these formats.
