### ISSUE TITLE
Import recipe file

### ISSUE THREAD

**Issue by JackKiefer** [JackKiefer/herms#8]
Add an option to import a `recipes.herms` file to the current installation's recipe book. It ought to look something like this:
`herms import {filename}`
This would more or less involve reading the given file and appending its contents to the herms installation's recipe book.

Some tips:
- See the `getRecipeBook` function in `herms.hs` to see how the file is read in
- Note how functions such as `remove` and `list` are handled via the `dispatch` function

**Comment by pdfrod** [comment]
Hi! I'd like to take a stab at this one, if it's OK.

**Comment by JackKiefer** [comment]
Go for it! :)

**Comment by JackKiefer** [comment]
Implemented by #24!
