### ISSUE TITLE
Generate a shopping list given several recipes

### ISSUE THREAD

**Issue by JackKiefer** [JackKiefer/herms#9]
Given several recipes and a serving size, generate an alphabetized list of ingredients that are required for those recipes. Maybe do this through a command similar to:
`herms shopfor "Tacos" "Pad Thai" -s2`
Which would give a shopping list for feeding two people a meal of Tacos and a meal of Pad Thai. Leveraging existing framework, one could also easily support selection through the recipe's index.
Also maybe come up with a better name than "shopfor" since "list" is already taken...

Tips:
- Leverage existing functions for parsing recipe names and serving size
- Don't worry about synonyms (e.g., scallions and green onions). We'll do something about that later down the line.
- Send the output to the terminal (nicely formatted, of course)

**Comment by vrom911** [comment]
How does this suppose to behave if ingredients are equal in different recipes (and what is equality of two ingredients? Should we care about equal attributes of ingredients to say they're equal?) ?

I can do this one, if it's okay.

**Comment by JackKiefer** [comment]
That's actually a really good question! Other digital recipe managers I've seen typically keep a dictionary of equivalent ingredient names for things like this. We can definitely work up to that point, but for now I think it would be fine to just list each ingredient and its quantity in alphabetical order (even if two recipes might call for the same ingredient). If they're alphabetized then the user will easily see duplicate ingredients right next to each other and know that they'll just need to do the math themselves.

If you want to go a step further than that, you could say that two ingredients are equal if their ``ingredientName`` strings are equal and group them together that way.   

Please, have at it! :)

**Comment by vrom911** [comment]
Great!
I would rather to compare both `ingredientName` and `unit`  to say that it's the same ingredient. As I see it, it could be 1 x bottle of milk and 500 ml of milk, so if just ignore units during comparing we can have 501 bottle or 501 ml of milk , which is not great, I guess..

Thanks! Almost done (I continue implementing this one with `optparse-applicative`)

**Comment by JackKiefer** [comment]
Merged #20
